parameters:
#    th_connect.example.class: TH\ConnectBundle\Example

services:
#    th_connect.facebook:
#        class: %th_connect.facebook

#    th_connect.example:
#        class: %th_connect.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
