<?php

namespace TH\ConnectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StreamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StreamRepository extends EntityRepository
{
    public function getAll()
    {
        return $this->getEntityManager()
            ->createQuery("SELECT s from THConnectBundle:Stream s WHERE s.type = 'link'")
            ->getResult();
    }

    public function getRandom()
    {
        $results = $this->getAll();

        return $results[ rand(0, count($results)-1) ];
    }
}
